services:
  rar2fs:
    image: zimme/rar2fs:latest
    init: true
    network_mode: none
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - MKNOD
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - '${RAR_SOURCE:?Set RAR_SOURCE}:/source'
      - '${RAR_DESTINATION:?Set RAR_DESTINATION}:/destination:rshared'
